In [1]:
import pandas as pd

ner_test = pd.read_csv('ner_test.csv')
ner_test.head()

Sentence #                                           Sentence  \
0  Sentence: 13390  In Tehran , the chief of Iran 's Revolutionary...   
1   Sentence: 3036  Even though both sites are now functioning , T...   
2   Sentence: 6014  Suspected U.S. drones have carried out at leas...   
3  Sentence: 34940  President Barack Obama has reaffirmed his beli...   
4   Sentence: 9605  They all decided that one person should get of...   

                                                 POS  \
0  ['IN', 'NNP', ',', 'DT', 'NN', 'IN', 'NNP', 'P...   
1  ['RB', 'IN', 'DT', 'NNS', 'VBP', 'RB', 'VBG', ...   
2  ['VBN', 'NNP', 'NNS', 'VBP', 'VBN', 'RP', 'IN'...   
3  ['NNP', 'NNP', 'NNP', 'VBZ', 'VBN', 'PRP$', 'N...   
4  ['PRP', 'DT', 'VBD', 'IN', 'CD', 'NN', 'MD', '...   

                                                 Tag  
0  ['O', 'B-tim', 'O', 'O', 'O', 'O', 'B-geo', 'O...  
1  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-or...  
2  ['O', 'B-geo', 'O', 'O', 'O', 'O', 'O', 'O', '...  
3  ['B-per', 'I-per', 'I-per', 'O', 'O', 'O', 'O'...  
4  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...

In [7]:
k = ner_test.iloc[0].to_list()
k

['Sentence: 13390',
 "In Tehran , the chief of Iran 's Revolutionary Guards , General Yahya Rahim Safavi , said Saturday his country would use ballistic missiles to defend itself if attacked .",
 "['IN', 'NNP', ',', 'DT', 'NN', 'IN', 'NNP', 'POS', 'NNP', 'NNPS', ',', 'NNP', 'NNP', 'NNP', 'NNP', ',', 'VBD', 'NNP', 'PRP$', 'NN', 'MD', 'VB', 'JJ', 'NNS', 'TO', 'VB', 'PRP', 'IN', 'VBN', '.']",
 "['O', 'B-tim', 'O', 'O', 'O', 'O', 'B-geo', 'O', 'B-geo', 'I-geo', 'O', 'B-org', 'I-org', 'I-org', 'I-org', 'O', 'O', 'B-tim', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']"]

In [19]:
k[1].split(), len(k[1].split())

(['In',
  'Tehran',
  ',',
  'the',
  'chief',
  'of',
  'Iran',
  "'s",
  'Revolutionary',
  'Guards',
  ',',
  'General',
  'Yahya',
  'Rahim',
  'Safavi',
  ',',
  'said',
  'Saturday',
  'his',
  'country',
  'would',
  'use',
  'ballistic',
  'missiles',
  'to',
  'defend',
  'itself',
  'if',
  'attacked',
  '.'],
 30)

In [18]:
# conver "['1', 'O']" to [1, 'O'] using eval
eval(k[2]), len(eval(k[2]))



(['IN',
  'NNP',
  ',',
  'DT',
  'NN',
  'IN',
  'NNP',
  'POS',
  'NNP',
  'NNPS',
  ',',
  'NNP',
  'NNP',
  'NNP',
  'NNP',
  ',',
  'VBD',
  'NNP',
  'PRP$',
  'NN',
  'MD',
  'VB',
  'JJ',
  'NNS',
  'TO',
  'VB',
  'PRP',
  'IN',
  'VBN',
  '.'],
 30)

In [20]:
test_crf = pd.read_csv('Test_CRF.csv')
test_crf.head()


Sentence  \
0  In Tehran , the chief of Iran 's Revolutionary...   
1  Even though both sites are now functioning , T...   
2  Suspected U.S. drones have carried out at leas...   
3  President Barack Obama has reaffirmed his beli...   
4  They all decided that one person should get of...   

                                                 POS  \
0  ['IN', 'NNP', ',', 'DT', 'NN', 'IN', 'NNP', 'P...   
1  ['RB', 'IN', 'DT', 'NNS', 'VBP', 'RB', 'VBG', ...   
2  ['VBN', 'NNP', 'NNS', 'VBP', 'VBN', 'RP', 'IN'...   
3  ['NNP', 'NNP', 'NNP', 'VBZ', 'VBN', 'PRP$', 'N...   
4  ['PRP', 'DT', 'VBD', 'IN', 'CD', 'NN', 'MD', '...   

                                                 Tag  
0  ['O', 'B-tim', 'O', 'O', 'O', 'O', 'B-geo', 'O...  
1  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-or...  
2  ['O', 'B-geo', 'O', 'O', 'O', 'O', 'O', 'O', '...  
3  ['B-per', 'I-per', 'I-per', 'O', 'O', 'O', 'O'...  
4  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...

In [11]:
import numpy as np

labels = np.array([1, 2, 3, 4, 5])
num_states = 6

state_features = np.zeros((len(labels), num_states))
# randomize the state features
state_features = np.random.randn(len(labels), num_states)

state_features

array([[ 0.65793846,  0.77677853,  0.94884681,  1.7783176 , -0.89389882,
        -0.69575738],
       [-0.43707965,  0.36450531,  0.05430084,  0.03855252, -1.15812843,
         0.01273876],
       [ 0.74664985, -0.77007466, -0.31346794,  1.27510681, -0.25458872,
        -1.56912045],
       [ 1.53502838, -0.23736561, -0.26380421,  0.80091985,  0.81204613,
        -0.5167686 ],
       [-2.46534099,  0.08445656,  0.01638625, -0.39267946,  1.02810797,
        -0.60292095]])

In [12]:
state_features[range(len(labels)), labels]

array([ 0.77677853,  0.05430084,  1.27510681,  0.81204613, -0.60292095])

In [13]:
state_features[3:8, [1,2,3,4]]

array([[-0.23736561, -0.26380421,  0.80091985,  0.81204613],
       [ 0.08445656,  0.01638625, -0.39267946,  1.02810797]])